# Generated by Django 3.1.4 on 2021-05-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
