# Generated by Django 3.1.4 on 2021-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_info', '0004_auto_20210529_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
