# Generated by Django 3.1.4 on 2021-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='contact',
            field=models.CharField(default=12345678, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='owner',
            field=models.CharField(default='Ronak', max_length=120),
            preserve_default=False,
        ),
    ]
